name: blg_linter
description: The linter rules for all Dart/Flutter projects.
version: 1.0.0
repository: https://github.com/Blago-Development/blg_linter

environment:
  sdk: ^3.10.0

dependencies:
  lints: ^6.0.0
