name: blg_linter
description: The linter rules for all Dart/Flutter projects.
version: 1.0.0
repository: https://github.com/Blago-Development/blg_linter

environment:
  sdk: ^3.3.2

dependencies:
  lints: ^5.0.0
